# Project: P3Examen1_JorgeZuniga
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = mainExamen1.o Equipos.o Liga.o Partido.o Tabla.o Puntos.o
LINKOBJ  = mainExamen1.o Equipos.o Liga.o Partido.o Tabla.o Puntos.o
LIBS     = -L"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/lib" -L"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/Alejandro/Desktop/c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = P3Examen1_JorgeZuniga.exe
CXXFLAGS = $(CXXINCS) -std=c++11 -g3
CFLAGS   = $(INCS) -std=c++11 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mainExamen1.o: mainExamen1.cpp
	$(CPP) -c mainExamen1.cpp -o mainExamen1.o $(CXXFLAGS)

Equipos.o: Equipos.cpp
	$(CPP) -c Equipos.cpp -o Equipos.o $(CXXFLAGS)

Liga.o: Liga.cpp
	$(CPP) -c Liga.cpp -o Liga.o $(CXXFLAGS)

Partido.o: Partido.cpp
	$(CPP) -c Partido.cpp -o Partido.o $(CXXFLAGS)

Tabla.o: Tabla.cpp
	$(CPP) -c Tabla.cpp -o Tabla.o $(CXXFLAGS)

Puntos.o: Puntos.cpp
	$(CPP) -c Puntos.cpp -o Puntos.o $(CXXFLAGS)
